SELECT  A.employee_id,
        A.first_name||' '||A.last_name AS NAME,
        A.email,
        A.phone_number,
        A.hire_date,
        A.job_id,
        B.JOB_TITLE,
        A.salary,
        A.commission_pct,
        A.manager_id,
        C.FIRST_NAME||' '||C.LAST_NAME AS MANAGER_NAME,
        D.FIRST_NAME||' '||D.LAST_NAME AS MANAGER_MANAGER_NAME,
        A.department_id,
        E.DEPARTMENT_NAME,
        E.LOCATION_ID,
        F.CITY,
        F.COUNTRY_ID,
        G.COUNTRY_NAME,
        G.REGION_ID,
        H.REGION_NAME
FROM employees a
INNER JOIN jobs b
ON (A.JOB_ID = B.JOB_ID)
LEFT JOIN EMPLOYEES C
ON (A.MANAGER_ID = C.EMPLOYEE_ID)
LEFT JOIN EMPLOYEES D
ON (C.MANAGER_ID = D.EMPLOYEE_ID)
LEFT JOIN DEPARTMENTS E
ON (A.DEPARTMENT_ID = E.DEPARTMENT_ID)
LEFT JOIN LOCATIONS F
ON (E.LOCATION_ID = F.LOCATION_ID)
LEFT JOIN COUNTRIES G
ON (F.COUNTRY_ID = G.COUNTRY_ID)
LEFT JOIN REGIONS H
ON (G.REGION_ID = H.REGION_ID);



SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM EMPLOYEES A
LEFT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);


SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM    EMPLOYEES A,
        DEPARTMENTS B
WHERE   A.DEPARTMENT_ID = B.DEPARTMENT_ID(+);


SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM    EMPLOYEES A
RIGHT JOIN DEPARTMENTS B
ON (A.DEPARTMENT_ID = B.DEPARTMENT_ID);



SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM    EMPLOYEES A,
        DEPARTMENTS B
WHERE   A.DEPARTMENT_ID(+) = B.DEPARTMENT_ID;

--Departamentos sin empleados
SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM    EMPLOYEES A,
        DEPARTMENTS B
WHERE   A.DEPARTMENT_ID(+) = B.DEPARTMENT_ID
AND     A.EMPLOYEE_ID IS NULL;


--Empleados sin departamento
SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM    EMPLOYEES A,
        DEPARTMENTS B
WHERE   A.DEPARTMENT_ID = B.DEPARTMENT_ID(+)
AND     B.DEPARTMENT_ID IS NULL;





---FULL OUTER JOIN

SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM    EMPLOYEES A,
        DEPARTMENTS B
WHERE   A.DEPARTMENT_ID = B.DEPARTMENT_ID(+)
UNION --UNE AMBAS CONSULTAS, TIENEN QUE TENER LA MISMA CANTIDAD DE CAMPOS Y LOS MISMOS TIPOS DE DATOS
SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM    EMPLOYEES A,
        DEPARTMENTS B
WHERE   A.DEPARTMENT_ID(+) = B.DEPARTMENT_ID
AND     A.EMPLOYEE_ID IS NULL;
