/*Crear una consulta para que muestre 3 niveles de categorías, mostrar para cada nivel el código y
el nombre de la categoría, utilizar producto cartesiano con el operador (+).*/

SELECT *
FROM TBL_CATEGORIAS;

--Categoria 2>-Categoria3->Categoria9


select  A.CODIGO_CATEGORIA, 
        A.NOMBRE, 
        B.NOMBRE AS NOMBRE_CATEGORIA_PADRE,
        C.NOMBRE AS NOMBRE_CATEGORIA_ABUELA
FROM    TBL_CATEGORIAS A,
        TBL_CATEGORIAS B,
        TBL_CATEGORIAS C
WHERE   A.CODIGO_CATEGORIA_PADRE = B.CODIGO_CATEGORIA(+)
AND     B.CODIGO_CATEGORIA_PADRE = C.CODIGO_CATEGORIA(+);

/*
Mostrar todas las aplicaciones con la siguiente información:
a. Nombre de la aplicación
b. Fecha de Lanzamiento
c. Año y mes de lanzamiento
d. Precio de la aplicación
e. Calificación promedio.
f. Cantidad de descargas exitosas de cada aplicación.
g. Cantidad de descargas fallidas de cada aplicación.
h. Cantidad de requerimientos de instalación.
i. Cantidad de nichos.
j. Monto total generado de las descargas de cada aplicación.

*/

SELECT B.CODIGO_APLICACION, A.NOMBRE_PRODUCTO, A.PRECIO,
        B.FECHA_LANZAMIENTO,
        TO_CHAR(B.FECHA_LANZAMIENTO,'MM-YYYY') ANIO_MES,
        NVL(C.CALIFICACION_PROMEDIO,0) CALIFICACION_PROMEDIO,
        NVL(D.CANTIDAD_DESCARGAS_EXITOSAS,0) CANTIDAD_DESCARGAS_EXITOSAS,
        NVL(E.CANTIDAD_DESCARGAS_FALLIDAS,0) CANTIDAD_DESCARGAS_FALLIDAS,
        NVL(F.CANTIDAD_NICHOS,0) CANTIDAD_NICHOS,
        NVL(D.CANTIDAD_DESCARGAS_EXITOSAS,0)*A.PRECIO AS MONTO_GENERADO
FROM TBL_PRODUCTOS A
INNER JOIN TBL_APLICACIONES B
ON (A.CODIGO_PRODUCTO = B.CODIGO_APLICACION)
LEFT JOIN (
    SELECT CODIGO_PRODUCTO, 
            AVG(VALORACION) AS CALIFICACION_PROMEDIO
    FROM TBL_CALIFICACIONES
    GROUP BY CODIGO_PRODUCTO
) C
ON (B.CODIGO_APLICACION = C.CODIGO_PRODUCTO)
LEFT JOIN (
    SELECT CODIGO_PRODUCTO, COUNT(*) CANTIDAD_DESCARGAS_EXITOSAS
    FROM TBL_HISTORIAL_DESCARGAS
    WHERE CODIGO_ESTATUS = 1
    GROUP BY CODIGO_PRODUCTO
) D
ON (B.CODIGO_APLICACION = D.CODIGO_PRODUCTO)
LEFT JOIN (
    SELECT CODIGO_PRODUCTO, COUNT(*) CANTIDAD_DESCARGAS_FALLIDAS
    FROM TBL_HISTORIAL_DESCARGAS
    WHERE CODIGO_ESTATUS = 2
    GROUP BY CODIGO_PRODUCTO
) E
ON (B.CODIGO_APLICACION = E.CODIGO_PRODUCTO)
LEFT JOIN (
    SELECT CODIGO_PRODUCTO, COUNT(*) CANTIDAD_NICHOS
    FROM TBL_NICHOS_X_PRODUCTO
    GROUP BY CODIGO_PRODUCTO
) F
ON (B.CODIGO_APLICACION = F.CODIGO_PRODUCTO);


